name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: CNAME
        run: |
            cd ./src/.vitepress/dist/
            touch CNAME
            echo "authup.net" > CNAME
